Loved this game. Still like this game, I've followed it since the beginning, I want to recommend it but can't. The idea is great, looks great, but it is a literal space sandbox with... emptiness. It came a long way, made giant leaps and bounds, but is painfully lifeless even with mods and the added contract stations, and feels as if it's lost focus and been put on backburner. Props to the devs for the occasional updates, but of late they're novelty blocks, some taken from mods, skins and little to no attention to the sometimes humorous physics bugs... and ludicrous amounts of dlc. Toilets are nice and all but new weapons and encounters would kinda be cooler. If there are any game changing plans on the horizon... it's difficult to tell. Take it for what you will.


So, after nearly 5 years and 3.5k hours on this game, I finally decided to take some time to give this game the review it deserved. Implicitly, the evidence is there for some types of people (looking at you, Lego fanatics and Minecraft nuts!), but if you have an attention span that has allowed you to get this far, BUY THIS GAME! I can not remember a game I am so eager to starting up like SE, every time. Fair warning, the learning curve can be quite daunting (as many hours as I have logged, I'm STILL learning stuff!) and the build time, depending on settings, may take hours to months to build. However, when you hear that "woosh" sound from your Gyros kicking in, and the hum of those engines when your ship leaves the station for the first time, its all worth it. Everytime. There will be your fair share of "WTF?! moments" but they are character building experiences at this point relatively for me because this game runs amazingly well now compared to earlier versions of the product. Also, the SE groups I have come to know makes me think that SE is one of the least toxic environments I have ever played in for any length of time. 11/10 recommend Oh yeah, and watch for Klang... Lastly, Keen, Marek, and our amazing modding community: Thank you for all of your hard work This is the game I have waited my entire life to play! YOU ROCK!!!

I once would have recommended this game but it seems KSH has lost either the ability or the motivation to improve the game outside of requiring RTM mechanics. Every patch and every DLC update makes the game less fun, more grindy without really adding any depth to the game. Large scale battles require massive amounts of PCU but cap at absurdly low numbers to allow a semblance of multiplayer. This was not always the case as I have been informed. Watching older SE YT videos showed how awesome the game was when it had drive and ambition coming out of EA. Now you play and wonder how they managed to do the things they did with ever increasing QoL updates that reduce quality of play and connectivity in MP. If the game's QoL requires a decrease in PCU or yield in mining then you only hamstring your efforts. Your game fails to live up to your aspirations shown in your trailer content. There are competitors who will eat your lunch if you don't change directions.

1,000 hours, I enjoyed them too. Most of those hours were pre-planets. As painful as it is for me to say this, Space Engineers was, and sadly still is nothing more than Marek Rosa's "Kick Starter" for a completely different company called "Good AI" KSH lost most of its senior staff and programmers for this new company, and SE has gone completely downhill since, Planets being the last "Gift" the original team left us. Look at it now....persistant bugs that existed pre-beta still alive and kicking, new, more nefarious bugs created by the inexperienced staff leftover from the original KSH (or maybe just cheap hired help) and planets that have been expanded on exactly zero times. Wait....nefarious bugs? ones that corrupt and subsequently delete every player-made blueprint.....yep, those exist too. I only recommend this game if it's on sale, 50% or more. There is fun to be had, just don't expect any ground breaking progress. The only thing keeping this game alive is modders, props to them. Any potential this game had left with the original staff.

I feel this dev is a fraud. Started the game 7 years ago, took in millions when EA, but spend all the money on pet project like AI, started Medieval Engineers, neglected Space Engineers for years, canceled Medieval Engineers, now wants money for "dlc" that should have been in the game from the start. Its a joke. But just like real life you can spend money only ones, but Keen/Marek spendt it on travelling the world talking and working on symposiums about some obscure AI program that has gone nowhere, while ignoring the community for long times at end. And people who think I lie, just google Keen and Marek, maybe go in waybackmachine, its well documented he spend our money and his time on a lot of other things then space engineers.
